# Numpy axis tutorial

In [4]:
from __future__ import print_function
import numpy as np

## Example matrix

In [7]:
# Though 2-dimensional matrices are simpler, it is best to perform the following operations on a 3d array,
# which is not too simple and not too complex.
A = np.array([[[1,-1.2],[4,-9],[7,-6],[10,-3]],
              [[2,-11],[50,-8],[8,-5],[11,-2]],
              [[3,-10],[6,-70],[0.9,-4],[12,-1]]])
print('Dimension:', A.ndim)
print('Shape:',A.shape)

Dimension: 3
Shape: (3, 4, 2)


In [10]:
print('Matrix A:')
print(A)

Matrix A:
[[[  1.   -1.2]
  [  4.   -9. ]
  [  7.   -6. ]
  [ 10.   -3. ]]

 [[  2.  -11. ]
  [ 50.   -8. ]
  [  8.   -5. ]
  [ 11.   -2. ]]

 [[  3.  -10. ]
  [  6.  -70. ]
  [  0.9  -4. ]
  [ 12.   -1. ]]]


## np.newaxis

In [9]:
print(A.shape)
print(A[np.newaxis].shape)
print(A[np.newaxis,:,:,:].shape)
print(A[np.newaxis,:,np.newaxis,:,:].shape)
print(A[:,:,:,np.newaxis])

(3, 4, 2)
(1, 3, 4, 2)
(1, 3, 4, 2)
(1, 3, 1, 4, 2)
[[[[  1. ]
   [ -1.2]]

  [[  4. ]
   [ -9. ]]

  [[  7. ]
   [ -6. ]]

  [[ 10. ]
   [ -3. ]]]


 [[[  2. ]
   [-11. ]]

  [[ 50. ]
   [ -8. ]]

  [[  8. ]
   [ -5. ]]

  [[ 11. ]
   [ -2. ]]]


 [[[  3. ]
   [-10. ]]

  [[  6. ]
   [-70. ]]

  [[  0.9]
   [ -4. ]]

  [[ 12. ]
   [ -1. ]]]]


## Reducing along an axis, for example by using max

In [16]:
print('Maximum over all elements:\n', A.max())

Maximum over all elements:
 50.0


In [21]:
# Let's start with the first dimension 
B = A.max(axis=0)
print('Maximum along first axis: B =\n', B)
print('A.shape: ', A.shape)
print('B.shape: ', B.shape)

Maximum along first axis: B =
 [[  3.   -1.2]
 [ 50.   -8. ]
 [  8.   -4. ]
 [ 12.   -1. ]]
A.shape:  (3, 4, 2)
B.shape:  (4, 2)


In [22]:
for j, k in zip(range(A.shape[1]), range(A.shape[2])):
    assert B[j,k] == max(A[i,j,k] for i in range(A.shape[0]))

In [23]:
# second dimension
B = A.max(axis=1)
print(B.shape)
print(B)

(3, 2)
[[ 10.   -1.2]
 [ 50.   -2. ]
 [ 12.   -1. ]]


In [24]:
# third and last dimension 
B = A.max(axis=2)
print(B.shape)
print(B)

(3, 4)
[[  1.    4.    7.   10. ]
 [  2.   50.    8.   11. ]
 [  3.    6.    0.9  12. ]]


## Broadcasting

In [29]:
try:
    A - A.max(axis=1)
except ValueError as e:
    print(e)

operands could not be broadcast together with shapes (3,4,2) (3,2) 


In [30]:
# The solution is to keep the specified axis in the result tensor but with a length 1 component.
# For that you need to use the more general numpy.amax function and set the parameter keepdims=True.
B = np.amax(A, axis=1, keepdims=True)
print(B.shape)
print(B)

(3, 1, 2)
[[[ 10.   -1.2]]

 [[ 50.   -2. ]]

 [[ 12.   -1. ]]]


In [32]:
# Now broadcasting is easy
print(A-B)
print((A - B).max(axis=1))

[[[ -9.    0. ]
  [ -6.   -7.8]
  [ -3.   -4.8]
  [  0.   -1.8]]

 [[-48.   -9. ]
  [  0.   -6. ]
  [-42.   -3. ]
  [-39.    0. ]]

 [[ -9.   -9. ]
  [ -6.  -69. ]
  [-11.1  -3. ]
  [  0.    0. ]]]
[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]


In [33]:
# By the way, amax is much more general and should be prefered, I think
np.amax(A - B, axis=1)

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [34]:
# For examples, just keep the the last dimension fixed, and calc the max over the first and second dimension
np.amax(A, axis=(0,1))

array([ 50.,  -1.])